# filepath: ./src/grafana/provisioning/datasources/datasources.yml
apiVersion: 1
datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
    uid: PA7F6415749A3297A
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      timeout: 30
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  
    isDefault: true
    editable: true
    uid: DS_PROMETHEUS