name: ft_transcendence

# these are common to all containers
x-common: &common
  env_file:
    - .env
  restart: on-failure
  networks:
    - transcendence_network
  init: true

services:
  postgres:
    <<: *common
    image: "postgres:16"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

# we could change to redis latest. we are not doing inception anymore
  redis:
    <<: *common
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  --save 60 1 --loglevel verbose
    healthcheck:
      test: ["CMD", "redis-cli", "ping"] 
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    <<: *common
    build: src/ft_transcendence_backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  game:
    <<: *common
    build: src/ft_transcendence_backend/game
    command: python3 -m uvicorn pong_game:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"

  caddy:
    <<: *common
    build:
      context: ./src/
      dockerfile: caddy/Dockerfile
    ports:
      - "8081:80"  # Run Caddy on a different port for testing
      - "8444:443"  # Run Caddy on a different port for testing
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    <<: *common
    build:
      context: ./src/
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src/nginx/logs:/var/log/nginx

  grafana:
    <<: *common
    build: 
      context: ./src/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=redis-datasource
      # Redis datasource configuration
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=redis-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./src/grafana:/etc/grafana/provisioning/datasources
      - ./src/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./src/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - redis

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - grafana
     
#   portainer:
#     <<: *common
#     build: src/portainer
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock:ro"
#       - portainer-data:/data
#     depends_on:
#       - nginx
#     networks:
#       - transcendence_network
#     ports:
#       - "9443:9443"

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  portainer-data:

networks:
  transcendence_network:
    name: transcendence_network
    driver: bridge
