name: ft_transcendence_test

x-common: &common
  env_file:
    - .env.test
  networks:
    - transcendence_test_network
  init: true

services:
  postgres_test:
    <<: *common
    image: "postgres:16"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    tmpfs: 
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_test:
    <<: *common
    image: "redis:alpine"
    ports:
      - "6381:6379"
    command: redis-server --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend_test:
    <<: *common
    build: 
      context: src/ft_transcendence_backend
      target: test
    depends_on:
      postgres_test:
        condition: service_healthy
      redis_test:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres_test
      - REDIS_HOST=redis_test
      - TESTING=true
    command: >
      sh -c "pytest --cov=. --cov-report=xml -v"

  game_test:
    <<: *common
    build: 
      context: src/ft_transcendence_backend/game
      target: test
    command: pytest --cov=. --cov-report=xml -v

networks:
  transcendence_test_network:
    name: transcendence_test_network
    driver: bridge