services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./game:/usr/share/nginx/html
    extra_hosts:
      - "host.docker.internal:host-gateway" 