global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp-relay.brevo.com:587'
  smtp_from: 'u-acht@pongbahnhof.de' 
  smtp_auth_username: '8881eb001@smtp-brevo.com'
  smtp_auth_password: 'Z8rOCaLt4b1EwTph'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'metter2ooo@gmail.com, ohoro@student.42berlin.de, alimpens@student.42berlin.de, hwiemann@student.42berlin.de'
    from: 'u-acht@pongbahnhof.de'
    send_resolved: true
    headers:
      subject: '{{ template "email.default.subject" . }}'
    html: '{{ template "email.default.html" . }}'