global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp-relay.brevo.com:587'  # From EMAIL_HOST and EMAIL_PORT
  smtp_from: '849697001@smtp-brevo.com'      # From EMAIL_HOST_USER
  smtp_auth_username: '849697001@smtp-brevo.com'  # From EMAIL_HOST_USER
  smtp_auth_password: 'kOmqRp1jT6KrPbWY'     # From EMAIL_HOST_PASSWORD
  smtp_require_tls: true                     # From EMAIL_USE_TLS

route:
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'metter2ooo@gmail.com'           
        send_resolved: true
        headers:
          subject: 'Test Alert Notification'
        html: >
          <b>Test Alert:</b> This is a test message.