server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://logstash:5044 

scrape_configs:

- job_name: postgresql
  static_configs:
  - targets:
      - localhost
    labels:
      job: postgresql
      __path__: /var/log/postgresql/*.log

- job_name: redis_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: redis
      __path__: /var/log/redis/redis-server.log

- job_name: backend_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: backend
      __path__: /app/logs/django.log

- job_name: caddy_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: caddy
      __path__: /var/log/caddy/*log
      agent: caddy-promtail

- job_name: grafana_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: grafana
      __path__: /var/log/grafana/grafana.log
  
  pipeline_stages:
  - json:
      expressions:
        duration: duration
        status: status
  - labels:
      duration:
      status: