global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'transcendence'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093'] 

scrape_configs:

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:80'] 

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  # - job_name: 'grafana'
  #   static_configs:
  #     - targets: ['grafana:3000']

  # - job_name: 'loki'
  #   static_configs:
  #     - targets: ['loki:3100']

  # - job_name: 'tempo'
  #   static_configs:
  #     - targets: ['tempo:3200']

  # - job_name: 'promtail'
  #   static_configs:
  #     - targets: ['promtail:9080']

  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   scrape_timeout: 5s
  #   static_configs:
  #     - targets: ['prometheus:9090'] 

  # - job_name: "node_exporter"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]