name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker Compose
        run: |
          docker compose up -d --build
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }} # Add secret
          GF_DEFAULT_THEME: "dark"
          DATABASE_URL: "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}"
          REDIS_HOST: "redis"
          REDIS_PORT: "6379"
          PORTAINER_VERSION: "2.14.2"
          PORTAINER_HOME: "/var/lib/portainer"
          KUBERNETES_SERVICE_HOST: ""
          KUBERNETES_SERVICE_PORT: ""

      - name: Run tests (if applicable)
        run: echo "Tests passed"

      - name: Stop Docker Compose
        run: docker compose down