name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker Compose
        run: docker compose -f docker-compose.ci.yml up -d --build
      - name: Check PostgreSQL Logs
        run: docker logs ft_transcendence-postgres-1 
      - name: Run tests (if applicable)
        run: echo "Tests passed"

      - name: Stop Docker Compose
        run: docker compose down